image: node:lts-alpine3.16

stages:
  - frontend_test
  - backend_test

frontend_test:
  stage: frontend_test
  cache:
    key: frontend-build-cache
    paths:
      - sources/frontend/node_modules/
    policy: pull
  script:
    - cd sources/frontend
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
    - npm test
  tags:
    - shared-fi

backend_test:
  stage: backend_test
  cache:
    key: backend-build-cache
    paths:
      - sources/backend/node_modules/
    policy: push
  script:
    - cd sources/backend
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
    - npm test
  artifacts:
    expire_in: 10 minutes
    when: on_success
  tags:
    - shared-fi