image: node:8.9.4

stages:
  - npm
  - test

npm:
  stage: npm
  script:
    - cd sources/frontend
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 10 minutes
    when: on_success
    paths:
      - node_modules/
  tags:
    - shared-fi

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm test
  artifacts:
    expire_in: 10 minutes
  tags:
    - shared-fi
