image: node:lts-alpine3.16

stages:
  - npm
  - test

npm:
  stage: npm
  script:
    - cd sources/frontend
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    key: build-cache
    paths:
      - sources/frontend/node_modules/
    policy: push
  artifacts:
    expire_in: 10 minutes
    when: on_success
    paths:
      - sources/frontend/node_modules/
  tags:
    - shared-fi

test:
  stage: test
  dependencies:
    - npm
  cache:
    key: build-cache
    paths:
      - sources/frontend/node_modules/
    policy: pull
  script:
    - cd sources/frontend
    - npm test
  artifacts:
    expire_in: 10 minutes
  tags:
    - shared-fi
